#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from turtlesim.srv import TeleportAbsolute

MAX = 10.99


class Sweeper(Node):
    def __init__(self):
        super().__init__("sweeper")

        self.left_to_right = True

        self.target = self.declare_parameter("target", "turtle1").value
        self.dx = float(self.declare_parameter("dx", "0.1").value)

        self.sweeper = Node("sweeper_client")
        self.client = self.sweeper.create_client(
            TeleportAbsolute, f"/{self.target}/teleport_absolute"
        )
        self.client.wait_for_service()

        self.pose = TeleportAbsolute.Request()

        while True:
            if self.left_to_right:
                self.pose.x += self.dx
                if self.pose.x >= MAX:
                    self.left_to_right = False
                    self.pose.x = MAX
                    self.pose.y += self.dx
                    self.pose.theta = 3.14
            else:
                self.pose.x -= self.dx
                if self.pose.x < 0.0:
                    self.left_to_right = True
                    self.pose.x = 0.0
                    self.pose.y += self.dx
                    self.pose.theta = 0.0
            if self.pose.y > MAX:
                self.pose.y = 0.0

            res = self.client.call_async(self.pose)
            rclpy.spin_until_future_complete(self.sweeper, res)


if __name__ == "__main__":

    rclpy.init()
    sweeper = Sweeper()

    rclpy.spin(sweeper)

    # clean exit on Ctrl-C
    sweeper.destroy_node()
    rclpy.shutdown()
